name: Build

on: [push, pull_request]

# as recommended by: https://github.com/actions/checkout/issues/1590
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  # === FreeBSD ===
  freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Build
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y curl gcc git cmake ruby libglvnd libglu freeglut mesa-devel mesa-dri alsa-lib doxygen
            gem install rake            
          run: |
            cd build
            cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_STATIC=On -DBUILD_WITH_LUA=On -DBUILD_WITH_MOON=On -DBUILD_WITH_FENNEL=On -DBUILD_WITH_WREN=On -DBUILD_WITH_RUBY=On -DBUILD_WITH_WASM=On -DBUILD_WITH_SCHEME=On -DBUILD_WITH_SQUIRREL=On -DBUILD_WITH_PYTHON=On -DBUILD_WITH_JS=On ..
            cmake --build . --parallel 2
            
      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-freebsd"
          path: |
            build/bin/tic80
            build/bin/*.so
